name = "ExtSquared"
uuid = "c689bb39-d3dc-4ca4-8d39-de08e98eb606"
authors = ["KristofferC <kristoffer.carlsson@juliacomputing.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"

[weakdeps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"

[extensions]
AExt = ["Colors"]
BExt = ["Colors", "Crayons"]
